# Generated by Django 4.0.4 on 2022-08-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registerdata',
            fields=[
                ('uname', models.CharField(max_length=50, primary_key='true', serialize=False)),
                ('mnumber', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='servicedetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('vname', models.CharField(max_length=50)),
                ('vnumber', models.CharField(max_length=50)),
                ('vtype', models.CharField(max_length=100, null='true')),
            ],
        ),
    ]
