# Generated by Django 4.0.4 on 2022-08-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('johnserviceapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ownermain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main', models.CharField(max_length=150)),
                ('adout', models.TextField()),
            ],
        ),
    ]
