# Generated by Django 4.0.4 on 2022-08-24 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('johnserviceapp', '0003_servicedetail_servicedel_alter_servicedetail_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
