# Generated by Django 4.0.4 on 2022-08-24 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('johnserviceapp', '0005_adminvalid'),
    ]

    operations = [
        migrations.CreateModel(
            name='delivery',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('flag', models.IntegerField()),
            ],
        ),
    ]
