# Generated by Django 4.0.4 on 2022-08-24 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('johnserviceapp', '0006_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedetail',
            name='flag',
            field=models.IntegerField(null='true'),
            preserve_default='true',
        ),
    ]
